ARDUINO_DIR  = /usr/share/arduino

BOARD_TAG    = pro5v
ARDUINO_PORT = /dev/ttyUSB0

TARGET       = autonomous

ARDUINO_LIBS = Wire Wire/utility

build-cli/autonomous.o: ../ledbar.h

include /usr/share/arduino/Arduino.mk
